Update Tiny.cup
java -cp cup.jar java_cup.Main -parser AnalizadorSintacticoTiny -symbols ClaseLexica -nopositions Tiny.cup
Error: Syntax error @ Symbol: COLON_COLON_EQUALS (unknown:41/10(0) - unknown:41/13(0))
Error : Illegal use of reserved word
------- CUP v0.11b beta 20140220 Parser Generation Summary -------
  2 errors and 0 warnings
  45 terminals, 29 non-terminals, and 78 productions declared,
  producing 0 unique parse states.
  0 terminals declared but not used.
  0 non-terminals declared but not used.
  0 productions never reduced.
  0 conflicts detected (0 expected).
  No code produced.
---------------------------------------------------- (v0.11b beta 20140220)

Co-Authored-By: Alai Miranda Blanco Lascurain <26670456+alaimiranda@users.noreply.github.com>
Co-Authored-By: Iago Barroso Ortega <148441502+gallo0o@users.noreply.github.com>